name: "Jester"
picture: "assets/img/picture.jpg"
bio: "Python/JavaScript Developer"
meta:
  lang: "en"
  description: "Forgive our Tresspasses"
  title: "Meaners"
  author: "Jester"
  siteUrl: "https://huuthienp.github.io/linktree/"
links:
  - name: "Telegram Channel"
    url: "https://t.me/+TzFF1iWC5DIzMDE0"
  - name: "Meaners Bot"
    url: "https://t.me/Meaners1chatbot"
  - name: "Support"
    url: "https://t.me/+TzFF1iWC5DIzMDE0"
  # - name: ""
  #   url: ""
theme: "custom"
